services:
  ur-demo-robot-api:
    environment:
      - ARCOR2_UR_ROBOT_IP=192.168.80.2
    volumes:
      - ./robot_calibration.yaml:/root/robot_calibration.yaml
  ur-demo-arserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://host.docker.internal:5012
  ur-demo-execution:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://host.docker.internal:5012